export const countryPhoneOptions = [
  { label: "Angola (+244)", value: "AO" },
  { label: "Anguilla (+1)", value: "AI" },
  { label: "Argentina (+54)", value: "AR" },
  { label: "Australia (+61)", value: "AU" },
  { label: "Austria (+43)", value: "AT" },
  { label: "Bahamas (+1)", value: "BS" },
  { label: "Bahrain (+973)", value: "BH" },
  { label: "Barbados (+1)", value: "BB" },
  { label: "Belgium (+32)", value: "BE" },
  { label: "Bolivia (+591)", value: "BO" },
  { label: "Bosnia And Herzegovina (+387)", value: "BA" },
  { label: "Brazil (+55)", value: "BR" },
  { label: "British Virgin Islands (+1)", value: "VG" },
  { label: "Bulgaria (+359)", value: "BG" },
  { label: "Cambodia (+855)", value: "KH" },
  { label: "Canada (+1)", value: "CA" },
  { label: "Cayman Islands (+1)", value: "KY" },
  { label: "Chile (+56)", value: "CL" },
  { label: "China (+86)", value: "CN" },
  { label: "Colombia (+57)", value: "CO" },
  { label: "Costa Rica (+506)", value: "CR" },
  { label: "Croatia (+385)", value: "HR" },
  { label: "Cyprus (+357)", value: "CY" },
  { label: "Czech Rep. (+420)", value: "CZ" },
  { label: "Denmark (+45)", value: "DK" },
  { label: "Dominica (+1)", value: "DM" },
  { label: "Dominican Republic (+1)", value: "DO" },
  { label: "Ecuador (+593)", value: "EC" },
  { label: "Egypt (+20)", value: "EG" },
  { label: "El Salvador (+503)", value: "SV" },
  { label: "Estonia (+372)", value: "EE" },
  { label: "Finland (+358)", value: "FI" },
  { label: "France (+33)", value: "FR" },
  { label: "Georgia (+995)", value: "GE" },
  { label: "Germany (+49)", value: "DE" },
  { label: "Ghana (+233)", value: "GH" },
  { label: "Greece (+30)", value: "GR" },
  { label: "Grenada (+1)", value: "GD" },
  { label: "Guatemala (+502)", value: "GT" },
  { label: "Hong Kong (+852)", value: "HK" },
  { label: "Hungary (+36)", value: "HU" },
  { label: "Iceland (+354)", value: "IS" },
  { label: "India (+91)", value: "IN" },
  { label: "Indonesia (+62)", value: "ID" },
  { label: "Ireland (+353)", value: "IE" },
  { label: "Israel (+972)", value: "IL" },
  { label: "Italy (+39)", value: "IT" },
  { label: "Ivory Coast (+225)", value: "CI" },
  { label: "Jamaica (+1)", value: "JM" },
  { label: "Japan (+81)", value: "JP" },
  { label: "Jordan (+962)", value: "JO" },
  { label: "Kazakhstan (+7)", value: "KZ" },
  { label: "Kenya (+254)", value: "KE" },
  { label: "Kyrgyzstan (+996)", value: "KG" },
  { label: "Laos (+856)", value: "LA" },
  { label: "Latvia (+371)", value: "LV" },
  { label: "Lithuania (+370)", value: "LT" },
  { label: "Luxembourg (+352)", value: "LU" },
  { label: "Macao (+853)", value: "MO" },
  { label: "Malaysia (+60)", value: "MY" },
  { label: "Malta (+356)", value: "MT" },
  { label: "Mauritius (+230)", value: "MU" },
  { label: "Mexico (+52)", value: "MX" },
  { label: "Moldova (+373)", value: "MD" },
  { label: "Monaco (+377)", value: "MC" },
  { label: "Montenegro (+382)", value: "ME" },
  { label: "Morocco (+212)", value: "MA" },
  { label: "Myanmar (+95)", value: "MM" },
  { label: "Netherlands (+31)", value: "NL" },
  { label: "New Zealand (+64)", value: "NZ" },
  { label: "Nicaragua (+505)", value: "NI" },
  { label: "Norway (+47)", value: "NO" },
  { label: "Oman (+968)", value: "OM" },
  { label: "Pakistan (+92)", value: "PK" },
  { label: "Panama (+507)", value: "PA" },
  { label: "Paraguay (+595)", value: "PY" },
  { label: "Peru (+51)", value: "PE" },
  { label: "Philippines (+63)", value: "PH" },
  { label: "Poland (+48)", value: "PL" },
  { label: "Portugal (+351)", value: "PT" },
  { label: "Puerto Rico (+1)", value: "PR" },
  { label: "Qatar (+974)", value: "QA" },
  { label: "Romania (+40)", value: "RO" },
  { label: "Russia (+7)", value: "RU" },
  { label: "Saint Lucia (+1)", value: "LC" },
  { label: "Saudi Arabia (+966)", value: "SA" },
  { label: "Serbia (+381)", value: "RS" },
  { label: "Singapore (+65)", value: "SG" },
  { label: "Slovakia (+421)", value: "SK" },
  { label: "Slovenia (+386)", value: "SI" },
  { label: "South Africa (+27)", value: "ZA" },
  { label: "South Korea (+82)", value: "KR" },
  { label: "Spain (+34)", value: "ES" },
  { label: "Sri Lanka (+94)", value: "LK" },
  { label: "Sweden (+46)", value: "SE" },
  { label: "Switzerland (+41)", value: "CH" },
  { label: "Tanzania (+255)", value: "TZ" },
  { label: "Thailand (+66)", value: "TH" },
  { label: "Trinidad and Tobago (+1)", value: "TT" },
  { label: "Tunisia (+216)", value: "TN" },
  { label: "Turkey (+90)", value: "TR" },
  { label: "Uganda (+256)", value: "UG" },
  { label: "Ukraine (+380)", value: "UA" },
  { label: "United Arab Emirates (+971)", value: "AE" },
  { label: "United Kingdom (+44)", value: "GB" },
  { label: "United States (+1)", value: "US" },
  { label: "Uruguay (+598)", value: "UY" },
  { label: "Venezuela (+58)", value: "VE" },
  { label: "Vietnam (+84)", value: "VN" },
];
