const languages = ['ln', 'cy', 'wo', 'cs', 'hy', 'nl', 'ceb', 'la', 'en-NZ', 'ss', 'lt', 'ne', 'fy', 'oc', 'yi', 'tt', 'bn', 'fr-CA', 'sw', 'th', 'ms', 'ka', 'pa', 'fi', 'ig', 'af', 'multi', 'eu', 'bs', 'ps', 'en-AU', 'si', 'ff', 'de', 'mt', 'km', 'pl', 'nl-BE', 'fr', 'en-IN', 'no', 'gu', 'lo', 'sk', 'ht', 'tk', 'bg', 'mn', 'su', 'ko', 'it', 'id', 'tl', 'zu', 'pt-BR', 'jv', 'et', 'ca', 'sl', 'ja', 'lb', 'gl', 'zh-TW', 'hi', 'ha', 'th-TH', 'lv', 'ast', 'sq', 'tr', 'ar', 'sv', 'haw', 'tg', 'lg', 'ba', 'mk', 'vi', 'hu', 'el', 'mi', 'en-US', 'kn', 'az', 'he', 'hr', 'ml', 'kk', 'es', 'br', 'sr', 'xh', 'uk', 'as', 'ilo', 'ru', 'gd', 'yo', 'da', 'sa', 'fa', 'es-419', 'bo', 'ur', 'my', 'nn', 'mo', 'so', 'mr', 'tn', 'sd', 'sn', 'uz', 'de-CH', 'fo', 'en-GB', 'zh', 'ro', 'pt', 'or', 'ga', 'ta', 'mg', 'en', 'be', 'am', 'te', 'is']

export const languageOptions = [
  { label: "English - default", value: "" },
  { label: "Afrikaans", value: "af" },
  { label: "Albanian", value: "sq" },
  { label: "Arabic", value: "ar" },
  { label: "Armenian", value: "hy" },
  { label: "Azerbaijani", value: "az" },
  { label: "Belarusian", value: "be" },
  { label: "Bengali", value: "bn" },
  { label: "Bosnian", value: "bs" },
  { label: "Bulgarian", value: "bg" },
  { label: "Catalan", value: "ca" },
  { label: "Chinese (Mandarin, Simplified)", value: "zh" },
  { label: "Chinese (Mandarin, Traditional)", value: "zh-TW" },
  { label: "Croatian", value: "hr" },
  { label: "Czech", value: "cs" },
  { label: "Danish", value: "da" },
  { label: "Dutch", value: "nl" },
  { label: "English", value: "en" },
  { label: "English (Australia)", value: "en-AU" },
  { label: "English (India)", value: "en-IN" },
  { label: "English (New Zealand)", value: "en-NZ" },
  { label: "English (UK)", value: "en-GB" },
  { label: "English (US)", value: "en-US" },
  { label: "English/Spanish mix", value: "multi" },
  { label: "Estonian", value: "et" },
  { label: "Finnish", value: "fi" },
  { label: "French", value: "fr" },
  { label: "French (Canada)", value: "fr-CA" },
  { label: "Galician", value: "gl" },
  { label: "Georgian", value: "ka" },
  { label: "German", value: "de" },
  { label: "German (Switzerland)", value: "de-CH" },
  { label: "Greek", value: "el" },
  { label: "Gujarati", value: "gu" },
  { label: "Haitian Creole", value: "ht" },
  { label: "Hausa", value: "ha" },
  { label: "Hebrew", value: "he" },
  { label: "Hindi", value: "hi" },
  { label: "Hungarian", value: "hu" },
  { label: "Icelandic", value: "is" },
  { label: "Indonesian", value: "id" },
  { label: "Italian", value: "it" },
  { label: "Japanese", value: "ja" },
  { label: "Javanese", value: "jv" },
  { label: "Kannada", value: "kn" },
  { label: "Kazakh", value: "kk" },
  { label: "Khmer", value: "km" },
  { label: "Korean", value: "ko" },
  { label: "Latvian", value: "lv" },
  { label: "Lithuanian", value: "lt" },
  { label: "Macedonian", value: "mk" },
  { label: "Malay", value: "ms" },
  { label: "Maori", value: "mi" },
  { label: "Marathi", value: "mr" },
  { label: "Nepali", value: "ne" },
  { label: "Norwegian", value: "no" },
  { label: "Persian", value: "fa" },
  { label: "Polish", value: "pl" },
  { label: "Portuguese", value: "pt" },
  { label: "Portuguese (Brazil)", value: "pt-BR" },
  { label: "Punjabi", value: "pa" },
  { label: "Romanian", value: "ro" },
  { label: "Russian", value: "ru" },
  { label: "Serbian", value: "sr" },
  { label: "Shona", value: "sn" },
  { label: "Slovak", value: "sk" },
  { label: "Slovenian", value: "sl" },
  { label: "Somali", value: "so" },
  { label: "Spanish", value: "es" },
  { label: "Spanish (Latin America)", value: "es-419" },
  { label: "Sundanese", value: "su" },
  { label: "Swahili", value: "sw" },
  { label: "Swedish", value: "sv" },
  { label: "Tagalog", value: "tl" },
  { label: "Tajik", value: "tg" },
  { label: "Tamil", value: "ta" },
  { label: "Telugu", value: "te" },
  { label: "Thai", value: "th" },
  { label: "Thai", value: "th-TH" },
  { label: "Tswana", value: "tn" },
  { label: "Turkish", value: "tr" },
  { label: "Ukrainian", value: "uk" },
  { label: "Urdu", value: "ur" },
  { label: "Vietnamese", value: "vi" },
  { label: "Welsh", value: "cy" },
];

export default languages
